version: "3.9"

services:
  c2rust:
    build:
      network: host
      context: .
    init: true
    network_mode: host
    working_dir: /host
    volumes:
      - type: bind
        source: "."
        target: /host
